controller_list:
  - name: "/xarm/L_xarm6_traj_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
